IS/urls.py
from django.urls import path, include
from IS import views
from IS.views import HeatTreatmentList, HeatTreatmentDetail

handler404 = 'IS.views.page_not_found'
app_name = 'IS'

urlpatterns = [
    path('main/', views.Main.as_view(), name='main'),
    # path('main/add', views.dynamic_fields_in_surfacing, name='add__'),
    path('main/<int:pk>/', views.Main.as_view(), name='main-update'),
    path('main/search/', views.search, name='search'),

    # Формы
    # path('main/add_gouging/', views.add_gouging, name='add_gouging'),
    # path('main/add_surfacing', views.add_surfacing, name='add_surfacing'),
    # path('main/add_heat_treatment', views.add_heat_treatment, name='add_heat_treatment'),
    # path('main/add_machining', views.add_machining, name='add_machining'),
    path(
        'main/add_primary_table',
        views.add_primary_table,
        name='add_primary_table'),

    path('add', HeatTreatmentList.as_view(), name='add'),
    path('detail/<int:pk>', HeatTreatmentDetail.as_view(), name='detail'),


]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from IS.views import index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', index, name='index'),
                  path('app/', include('IS.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
              ] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/add_gouging.html
{% extends 'base.html' %}
{#TODO: Доделать оформление формы#}
{% load static %}
{% block static %}
    <meta charset="UTF-8">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/locale_ru.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block title %}
    <title>Добавить строжку</title>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                        <form role="form" class="form-control-lg mt-4" method="post" id="gouging_form"
                              action="{% url 'IS:add_gouging' %}">
                            {% csrf_token %}
                            <h2 class="form-signin-heading">Добавить строжку</h2>
                            {% csrf_token %}
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            {% for field in form.visible_fields %}
                                {{ field.errors }}
                                {{ field.help_text }} <br>
                                {{ field }} <br>
                            {% endfor %}

                            <button class="btn btn-primary mt-2" type="submit">Добавить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}
        <script>
            $(function () {
                $('#example').datetimepicker(
                    {
                        locale: moment.locale('locale_ru.js'),
                        showClear: true,
                        showTodayButton: true,
                    }
                );
            });
        </script>
    {% endblock %}
{% endblock %}

templates/add_heat_treatment.html
{% extends 'base.html' %}
{#TODO: Доделать оформление формы#}
{% load static %}
{% block static %}
    <meta charset="UTF-8">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/locale_ru.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block title %}
    <title>Добавить термообработку</title>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                        <form role="form" class="form-control-lg mt-4" method="post" id="gouging_form"
                              action="{% url 'IS:add_heat_treatment' %}">
                            {% csrf_token %}
                            <h2 class="form-signin-heading">Добавить термообработку</h2>
                            {% csrf_token %}
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            {% for field in form.visible_fields %}
                                {{ field.errors }}
                                {{ field.help_text }} <br>
                                {{ field }} <br>
                            {% endfor %}
                            <button class="btn btn-primary mt-2" type="submit">Добавить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}
        <script>
            $(function () {
                $('#example').datetimepicker(
                    {
                        locale: moment.locale('locale_ru.js'),
                        showClear: true,
                        showTodayButton: true,
                    }
                );
            });
        </script>
    {% endblock %}
{% endblock %}

templates/add_machining.html
{% extends 'base.html' %}
{#TODO: Доделать оформление формы#}
{% load static %}
{% block static %}
    <meta charset="UTF-8">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/locale_ru.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block title %}
    <title>Добавить механообработку</title>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                        <form role="form" class="form-control-lg mt-4" method="post" id="gouging_form"
                              action="{% url 'IS:add_machining' %}">
                            {% csrf_token %}
                            <h2 class="form-signin-heading">Добавить механообработку</h2>
                            {% csrf_token %}
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            {% for field in form.visible_fields %}
                                {{ field.errors }}
                                {{ field.help_text }} <br>
                                {{ field }} <br>
                            {% endfor %}
                            <button class="btn btn-primary mt-2" type="submit">Добавить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}
        <script>
            $(function () {
                $('#example').datetimepicker(
                    {
                        locale: moment.locale('locale_ru.js'),
                        showClear: true,
                        showTodayButton: true,
                    }
                );
            });
        </script>
    {% endblock %}
{% endblock %}

templates/add_primary_table.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block static %}
    <meta charset="UTF-8">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/locale_ru.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}

{% block title %}
    <title>Добавить главную таблицу</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-md-center">
            <form class="form-control border-0" method="post" action="{% url 'IS:add_primary_table' %}" novalidate>
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col">

                        {% for hidden_field in form.hidden_fields %}
                            {{ hidden_field }}
                        {% endfor %}

                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {% for error in form.non_field_errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}

                        {% for field in form.visible_fields %}
                            <div class="form-group">
                                {{ field.label_tag }}

                                {% if form.is_bound %}
                                    {% if field.errors %}
                                        {% render_field field class="form-control is-invalid" %}
                                        {% for error in field.errors %}
                                            <div class="invalid-feedback">
                                                {{ error }}
                                            </div>
                                        {% endfor %}
                                    {% else %}
                                        {% render_field field class="form-control is-valid" %}
                                    {% endif %}
                                {% else %}
                                    {% render_field field class="form-control" %}
                                {% endif %}

                                {% if field.help_text %}
                                    <small class="form-text text-muted">{{ field.help_text }}</small>
                                {% endif %}
                            </div>
                        {% endfor %}

                        {% include 'modal/gouging.html' %}
                        {% include 'modal/surfacing.html' %}
                        {% include 'modal/heat_treatment.html' %}
                        {% include 'modal/machining.html' %}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block">Создать</button>
            </form>
        </div>
    </div>
    {% block scripts %}
        <script>
            $(function () {
                $('#pt_pickdatetime').datetimepicker(
                    {
                        locale: moment.locale('locale_ru.js'),
                        showClear: true,
                        showClose: true,
                        showTodayButton: true,
                        ignoreReadonly: true,
                        allowInputToggle: true,
                    }
                );
            });
        </script>

        <script>
            $(function () {
                $('#gouging_pickdatetime').datetimepicker(
                    {
                        locale: moment.locale('locale_ru.js'),
                        showClear: true,
                        showClose: true,
                        showTodayButton: true,
                        ignoreReadonly: true,
                        allowInputToggle: true
                    }
                );
            });
        </script>

        <script>
            $(function () {
                $('#surfacing_pickdatetime').datetimepicker(
                    {
                        locale: moment.locale('locale_ru.js'),
                        showClear: true,
                        showClose: true,
                        showTodayButton: true,
                        ignoreReadonly: true,
                        allowInputToggle: true
                    }
                );
            });
        </script>

        <script>
            $(function () {
                $('#heat_treatment_pickdatetime').datetimepicker(
                    {
                        locale: moment.locale('locale_ru.js'),
                        showClear: true,
                        showClose: true,
                        showTodayButton: true,
                        ignoreReadonly: true,
                        allowInputToggle: true
                    }
                );
            });
        </script>

        <script>
            $(function () {
                $('#machining_pickdatetime').datetimepicker(
                    {
                        locale: moment.locale('locale_ru.js'),
                        showClear: true,
                        showClose: true,
                        showTodayButton: true,
                        ignoreReadonly: true,
                        allowInputToggle: true,
                        widgetPositioning: {
                            horizontal: 'auto',
                            vertical: 'bottom'
                        }
                    }
                );
            });
        </script>
    {% endblock %}
{% endblock %}

templates/add_surfacing.html
{% extends 'base.html' %}
{#TODO: Доделать оформление формы#}
{% load static %}
{% block static %}
    <meta charset="UTF-8">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/locale_ru.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block title %}
    <title>Добавить наплавку</title>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                        <form role="form" class="form-control-lg mt-4" method="post" id="gouging_form"
                              action="{% url 'IS:add_surfacing' %}">
                            {% csrf_token %}
                            <h2 class="form-signin-heading">Добавить наплавку</h2>
                            {% csrf_token %}
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            {% for field in form.visible_fields %}
                                {{ field.errors }}
                                {{ field.help_text }} <br>
                                {{ field }} <br>
                            {% endfor %}
                            <button class="btn btn-primary mt-2" type="submit">Добавить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% block scripts %}
        <script>
            $(function () {
                $('#example').datetimepicker(
                    {
                        locale: moment.locale('locale_ru.js'),
                        showClear: true,
                        showTodayButton: true,
                    }
                );
            });
        </script>
    {% endblock %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru-RU">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block static %}
        <!-- Bootstrap CSS -->

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {% endblock %}
    <link rel="shortcut icon" href="media/images/favicon.ico" type="image/x-icon">
    {% block title %}
        <title>Neweld</title>
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'index' %}">Neweld</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'IS:main' %}">Все таблицы <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/admin/">admin</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'IS:add_primary_table' %}">Добавить главную таблицу</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'IS:add' %}">Добавить термообработку</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'IS:search' %}" method="get">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Поиск оснастки" aria-label="Search" name="q"
                   value="{{ request.get.q }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
        </form>
    </div>
</nav>


{% block content %}

{% endblock %}



{% block scripts %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}
</body>
</html>

templates/heat_treatment_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    {% csrf_token %}
        {{ form.as_p }}
        <button class="btn badge-primary" type="submit">Update</button>
    </div>
{% endblock %}

templates/heat_treatment_list.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h2 class="display-4">Термообработка</h2>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Итоговая твердость</th>
                <th scope="col">Начальная дата</th>
            </tr>
            </thead>
            <tbody>
            {% for record in heat_treatment %}
                <tr class="clickable-row" data-href='{% url 'IS:detail' record.id %}'>
                    <th scope="row">{{ record.id }}</th>
                    <td>{{ record.final_hardness }}</td>
                    <td>{{ record.start_date }}</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>


        {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active"><span class="page-link">{{ i }} <span
                                    class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <div id="carouselExampleControls" class="carousel slide mt-4 mb-4" data-ride="carousel">
                    <div class="carousel-inner">
                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleIndicators" data-slide-to="0"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-item">
                            <img class="d-block w-100"
                                 src="https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/ZosI56d/flying-particles-25-welding-sparks-background_ng-t20dlx__F0007.png"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item active">
                            <img class="d-block w-100"
                                 src="https://www.awebtoknow.com/wp-content/uploads/2017/10/best-welding-gloves.jpg"
                                 alt="Second slide">
                            <div class="carousel-caption d-none d-md-block">
                                <a class="btn btn-lg btn-secondary" href="{% url 'IS:main' %}">Все таблицы</a>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100"
                                 src="https://trweldingandfabrication.com/wp-content/themes/wcon/images/sliders/01.jpg"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <a href="{% url 'IS:main' %}" class="btn btn-lg btn-outline-primary mb-4 btn-block">Все оснастки</a>
                <a href="{% url 'IS:add_primary_table' %}" class="btn btn-lg btn-outline-primary mb-4 btn-block">Добавить оснастку</a>
            </div>
            <!-- /.col-sm -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
{% endblock %}

templates/main.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">

            <div class="col-sm text-light mt-4">
                {% if tables %}
                    <table class="table table-hover table-bordered table-dark ">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Номер оснастки</th>
                            <th scope="col">Литера</th>
                            <th scope="col">Строжка</th>
                            <th scope="col">Наплавка</th>
                            <th scope="col">Термообработка</th>
                            <th scope="col">Механообработка</th>
                            <th scope="col">Дата поступления штампа</th>
                            <th scope="col">Заказчик</th>
                            <th scope="col">Чертёж</th>
                        </tr>
                        </thead>

                        {% for table in tables %}
                            <tbody>
                            <tr>
                                <th scope="row">{{ table.id }}</th>
                                <td>{{ table.number }}</td>
                                <td>{{ table.letter }}</td>
                                <td>{{ table.gouging }}</td>
                                <td>{{ table.surfacing }}</td>
                                <td>{{ table.heat_treatment }}</td>
                                <td>{{ table.machining }}</td>
                                <td>{{ table.received_stamp_date }}</td>
                                <td>{{ table.customer }}</td>
                                <td>{{ table.scheme }}</td>
                            </tr>
                            </tbody>
                        {% endfor %}

                    </table>
                {% else %}
                    <p class="display-1">Таблицы отсутствуют!</p>
                {% endif %}
            </div>
            <!-- /.col-sm -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
{% endblock %}

templates/primary_tables_edit.html
{% extends 'base.html' %}

<form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"></button>
</form>

templates/search.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">

            <div class="col-sm text-light mt-4">
                {% if tables %}

                    <table class="table table-hover table-bordered table-dark ">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Номер оснастки</th>
                            <th scope="col">Литера</th>
                            <th scope="col">Строжка</th>
                            <th scope="col">Наплавка</th>
                            <th scope="col">Термообработка</th>
                            <th scope="col">Механообработка</th>
                            <th scope="col">Дата поступления штампа</th>
                            <th scope="col">Заказчик</th>
                            <th scope="col">Чертёж</th>
                        </tr>
                        </thead>

                        {% for table in tables %}
                            <tbody>
                            <tr>
                                <th scope="row">{{ table.id }}</th>
                                <td>{{ table.number }}</td>
                                <td>{{ table.letter }}</td>
                                <td>{{ table.gouging }}</td>
                                <td>{{ table.surfacing }}</td>
                                <td>{{ table.heat_treatment }}</td>
                                <td>{{ table.machining }}</td>
                                <td>{{ table.received_stamp_date }}</td>
                                <td>{{ table.customer }}</td>
                                <td>{{ table.scheme }}</td>
                            </tr>

                            </tbody>
                        {% endfor %}
                    </table>
                {% else %}
                    <p class="display-1 text-center">Таких таблиц нет!</p>
                {% endif %}
            </div>
            <!-- /.col-sm -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->


{% endblock %}